name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test || true

    - name: Archive app
      run: |
        tar -czf app.tar.gz .

    - name: Upload to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        source: "app.tar.gz"
        target: "~"

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        script: |
          mkdir -p ~/app
          tar -xzf ~/app.tar.gz -C ~/app
          cd ~/app
          npm install --production
          pkill -f "node server.js" || true
          nohup node server.js > output.log 2>&1 &
